default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: library_development

test:
  <<: *default
  database: library_test
  
production:
  <<: *default
  database: library_production
  username: library
  password: <%= ENV['LIBRARY_DATABASE_PASSWORD'] %>
